### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by DmitryEfimenko** [openpassphrase/opp#18]
The website should probably provide a way for a user to download all their data. Excel format or CSV.
Not sure if this needs to be in the API though. In theory this could be just a client side functionality since the client has all the data when user is logged in.

Thoughts?

**Comment by abashmak** [comment]
It's a nice feature, but I would also argue that it's better handled in the client. The client can easily format the JSON response from fetchAll into a CSV.

**Comment by DmitryEfimenko** [comment]
ok, I'll move this issue into the opp-web
